use_gpu: True
seed: 4
device: 0
early_stop:
  patience: 0
federate:
  mode: standalone
  client_num: 50
  total_round_num: 200
  save_to: "llama_gsm_fed_rolora_r2_30*200.ckpt"
  save_freq: 20
  share_local_model: True
  online_aggr: False
data:
  root: data/
  type: 'gsm8k@llm'
  splits: [0.84,0.07,0.07]
  splitter: 'iid'
llm:
  cache:
    model: '/scratch/ssd004/scratch/chensy/hf_home/'
  tok_len: 5000
  chat:
    max_len: 5000
  adapter:
    use: True
    args: [ { 'adapter_package': 'peft', 'adapter_method': 'lora', 'r': 2, 'lora_alpha': 16, 'lora_dropout': 0.05 } ]
dataloader:
  batch_size: 1
model:
  type: 'meta-llama/Llama-2-7b-hf@huggingface_llm'
train:
  local_update_steps: 30
  batch_or_epoch: batch
  optimizer:
    lr: 0.00002
    weight_decay: 0.00002
  is_enable_half: True
criterion:
  type: CrossEntropyLoss
trainer:
  type: llmtrainer
eval:
  freq: 20
  metrics: ['loss']
  best_res_update_round_wise_key: val_loss
  count_flops: False